interface FormData {
  fullName: string;
  fullNameAr?: string;
  title: string;
  titleAr?: string;
  graduationYear: string;
  university: string;
  universityAr?: string;
  phone: string;
  whatsapp: string;
  email: string;
  instagram?: string;
  facebook?: string;
  linkedin?: string;
  clinicName?: string;
  clinicNameAr?: string;
  locationAddress?: string;
  locationAddressAr?: string;
  locationLat?: string;
  locationLng?: string;
  profilePhoto?: string | null;
  clinicalSkills?: string[];
  digitalSkills?: string[];
  softSkills?: string[];
  clinicalSkillsAr?: string[];
  digitalSkillsAr?: string[];
  softSkillsAr?: string[];
  timeline?: { year: string; event: string; eventAr?: string }[];
  cases?: {
    category: string;
    categoryAr?: string;
    customCategory?: string;
    title: string;
    titleAr?: string;
    photo?: string | null;
  }[];
}

export function generateHugoToml(form: FormData): string {
  const sanitize = (str?: string) => (str || '').replace(/"/g, '\\"').trim();

  let toml = `# Generated by PortfolioHubs\n\n`;
  toml += `baseURL = "https://portfoliohubs.github.io/${sanitize(form.fullName).toLowerCase().replace(/[^a-z0-9]/g, '')}/"\n`;
  toml += `title = "${sanitize(form.fullName)}"\n`;
  toml += `theme = "doctor-portfolio"\n`;
  toml += `defaultContentLanguage = "en"\n\n`;

  toml += `[params]\n`;
  toml += `  fullName = "${sanitize(form.fullName)}"\n`;
  toml += `  fullNameAr = "${sanitize(form.fullNameAr)}"\n`;
  toml += `  title = "${sanitize(form.title)}"\n`;
  toml += `  titleAr = "${sanitize(form.titleAr)}"\n`;
  toml += `  graduationYear = "${sanitize(form.graduationYear)}"\n`;
  toml += `  university = "${sanitize(form.university)}"\n`;
  toml += `  universityAr = "${sanitize(form.universityAr)}"\n`;
  toml += `  phone = "${sanitize(form.phone)}"\n`;
  toml += `  whatsapp = "${sanitize(form.whatsapp)}"\n`;
  toml += `  email = "${sanitize(form.email)}"\n`;
  toml += `  instagram = "${sanitize(form.instagram)}"\n`;
  toml += `  facebook = "${sanitize(form.facebook)}"\n`;
  toml += `  linkedin = "${sanitize(form.linkedin)}"\n`;
  toml += `  clinicName = "${sanitize(form.clinicName)}"\n`;
  toml += `  clinicNameAr = "${sanitize(form.clinicNameAr)}"\n`;
  toml += `  locationAddress = "${sanitize(form.locationAddress)}"\n`;
  toml += `  locationAddressAr = "${sanitize(form.locationAddressAr)}"\n`;
  toml += `  profilePhoto = "${sanitize(form.profilePhoto || '')}"\n\n`;

  // Skills
  toml += `  clinicalSkills = [${(form.clinicalSkills || []).map((s) => `"${sanitize(s)}"`).join(', ')}]\n`;
  toml += `  clinicalSkillsAr = [${(form.clinicalSkillsAr || []).map((s) => `"${sanitize(s)}"`).join(', ')}]\n`;
  toml += `  digitalSkills = [${(form.digitalSkills || []).map((s) => `"${sanitize(s)}"`).join(', ')}]\n`;
  toml += `  digitalSkillsAr = [${(form.digitalSkillsAr || []).map((s) => `"${sanitize(s)}"`).join(', ')}]\n`;
  toml += `  softSkills = [${(form.softSkills || []).map((s) => `"${sanitize(s)}"`).join(', ')}]\n`;
  toml += `  softSkillsAr = [${(form.softSkillsAr || []).map((s) => `"${sanitize(s)}"`).join(', ')}]\n\n`;

  // Timeline
  (form.timeline || []).forEach((m, idx) => {
    toml += `[[params.timeline]]\n`;
    toml += `  year = "${sanitize(m.year)}"\n`;
    toml += `  event = "${sanitize(m.event)}"\n`;
    toml += `  eventAr = "${sanitize(m.eventAr)}"\n\n`;
  });

  // Cases
  (form.cases || []).forEach((c, idx) => {
    toml += `[[params.cases]]\n`;
    toml += `  category = "${sanitize(c.category === 'custom' ? c.customCategory : c.category)}"\n`;
    toml += `  categoryAr = "${sanitize(c.categoryAr)}"\n`;
    toml += `  title = "${sanitize(c.title)}"\n`;
    toml += `  titleAr = "${sanitize(c.titleAr)}"\n`;
    toml += `  photo = "${sanitize(c.photo || '')}"\n\n`;
  });

  return toml;
}
