export interface LiveExample {
  photo: string;
  name: string;
  link: string;
}

export interface CaseCategory {
  id: string;
  en: string;
  ar: string;
}

export const CONFIG = {
  brand: {
    name: "PortfolioHubs",
    slogan: "الاسنانجى لازم يتدلع",
    sloganEn: "The Dentist Deserves to Shine",
    logoUrl: "https://github.com/user-attachments/assets/fef6c67d-5ed0-4459-b41d-4c288ab48163",
    favicon: "https://github.com/user-attachments/assets/fef6c67d-5ed0-4459-b41d-4c288ab48163",
  },
  social: {
    facebook: "https://www.facebook.com/share/1CRkHCYgen/",
    instagram: "https://www.instagram.com/portfoliohubs?igsh=MTF3d2tzcXU0cm41cw==",
    whatsapp: "https://wa.me/201271476215",
  },
  whatsapp: {
    destinationNumber: "201271476215",
    message: "Hi! Here is my portfolio configuration file from PortfolioHubs.",
  },
  home: {
    headline: "Build Your Professional Dental Portfolio & CV",
    subheadline: "الاسنانجى لازم يتدلع",
    portfolioButtonTitle: "Portfolio in Google & AI Search",
    portfolioButtonSubtitle: "Professional with just 499 LE • appearing in Google search & AI tools answers as ChatGPT",
    cvButtonTitle: "CV PDF Maker for free",
    cvButtonSubtitle: "Easy • Free • No account needed",
    features: [
      "100% Free CV Maker",
      "Google Search & AI Ready",
      "No Coding Required",
      "Mobile & Tablet Friendly",
    ],
    usersCount: "23007",
    usersCountLabel: "users till now (updated weekly)",
  },
  portfolioIntro: {
    title: "For Who is this Portfolio website?",
    stepLabel: "for who ?",
    content: [
      "for who this ?",
      "for dentist need :",
      "1. appear in google search",
      "2. appear in Chatgpt, Gemini, all other AI tools answers",
      "3. need official website",
      "4. professional",
      "5. creative permanent marketing",
    ],
    liveExamples: [
      { photo: "https://github.com/user-attachments/assets/97ba84f2-8190-4ea6-b396-c6beb0bb3572", name: "Dr.Michael Nabil", link: "https://portfoliohubs.github.io/drmichaelnabil/" },
      { photo: "https://github.com/user-attachments/assets/1c669ac9-2b53-4c18-b396-821409c6ada4", name: "Dr. Hanan Sakr", link: "https://portfoliohubs.github.io/drhanansakr/" },
      { photo: "https://github.com/user-attachments/assets/1fd807ab-3d10-41ee-9d63-57f097d1eab6", name: "Dr. Roaa Adel", link: "https://portfoliohubs.github.io/drroaaadel/" },
      { photo: "https://github.com/user-attachments/assets/57302af1-dbce-4a6c-8773-f74fc6d9669f", name: "Dr. Hossam Lotfy", link: "https://portfoliohubs.github.io/drhossamlotfy/" },
      { photo: "https://github.com/user-attachments/assets/b9c66a94-55d2-4fbd-9500-e7acdc01a9d3", name: "Dr. Rawan Mahmoud", link: "https://portfoliohubs.github.io/drrawanmahmoud/" },
      { photo: "https://github.com/user-attachments/assets/f8c883ac-4a8e-4e0e-ab04-04ec7c771eed", name: "Dr. Abanoub Nageh", link: "https://portfoliohubs.github.io/drabanoubnageh/" },
      { photo: "https://github.com/user-attachments/assets/32d363af-0c59-4bae-9ba3-97330259af67", name: "Dr. Abrar Kamal", link: "https://portfoliohubs.github.io/drabrarkamal/" },
      { photo: "https://github.com/user-attachments/assets/9061d11c-6854-4d58-b240-db0314d816eb", name: "Dr. Youstina Elkes Ghabrial", link: "https://portfoliohubs.github.io/dryoustinaelkesghabrial" },
      { photo: "https://github.com/user-attachments/assets/7e5e9e46-5a49-4c65-af7e-e7bb21601bdc", name: "Dr. Eslam Anas Abdelwahab", link: "https://portfoliohubs.github.io/dreslamanas/" },
    ] as LiveExample[],
  },
  payWhatYouWant: {
    enabled: "off",
    buttonLabel: "Pay What You Want",
    whatsappNumber: "201271476215",
    whatsappMessage: "i love your support ,i need to pay",
  },
  steps: {
    personal: "Personal Info",
    contact:  "Contact Details",
    photo:    "Profile Photo",
    skills:   "Professional Skills",
    timeline: "Career Timeline",
    cases:    "Clinical Cases",
    preview:  "Preview & Download",
  },
  labels: {
    fullNameEn:          "Full Name (English)",
    fullNameAr:          "الاسم بالكامل (عربي)",
    titleEn:             "Title / Role (English)",
    titleAr:             "المسمى المهني (عربي)",
    graduationYear:      "Graduation Year",
    universityEn:        "University / Faculty (English)",
    universityAr:        "الجامعة / الكلية (عربي)",
    phone:               "Phone",
    whatsapp:            "WhatsApp",
    email:               "Email",
    website:             "Your Link (Professional Page — optional)",
    profilePhoto:        "Profile Photo",
    profilePhotoHint:    "Upload a clear, front-facing photo. Any size accepted.",
    clinicalSkills:      "Clinical Skills",
    digitalSkills:       "Digital Skills",
    softSkills:          "Soft Skills",
    skillInputHint:      "Type a skill and click Add",
    addSkill:            "Add",
    timeline:            "Career Timeline",
    timelineHint:        "Add milestones that appear on the Education page",
    addMilestone:        "Add Milestone",
    milestoneYear:       "Year",
    milestoneEn:         "Event (English)",
    milestoneAr:         "Event (Arabic)",
    cases:               "Clinical Cases",
    casesHint:           "Select multiple photos at once — each photo becomes a case entry",
    casesUnlimitedLabel: "Unlimited Cases",
    selectPhotos:        "Select Case Photos",
    category:            "Category",
    selectCategory:      "Select a category",
    customCategory:      "Custom category",
    caseTitleEn:         "Case Title (English)",
    caseTitleAr:         "Case Title (Arabic)",
    caseSubtitle:        "Subtitle / Description (optional)",
    previewTitle:        "Review Your Data",
    previewSubtitle:     "Check everything before downloading",
  },
  placeholders: {
    fullNameEn:     "Dr. Mohammed Ahmed",
    fullNameAr:     "د. محمد أحمد",
    titleEn:        "Internship Dentist, Orthodontist",
    titleAr:        "طبيب أسنان متدرب, اخصائى تقويم",
    graduationYear: "2025",
    universityEn:   "Faculty of Dentistry, University Name",
    universityAr:   "كلية طب الأسنان، اسم الجامعة",
    phone:          "+20 123 456 7890",
    whatsapp:       "+20 123 456 7890",
    email:          "doctor@example.com",
    website:        "Facebook or Instagram or LinkedIn,...etc",
    clinicalSkill:  "e.g. Oral Surgery",
    digitalSkill:   "e.g. Dental Photography",
    softSkill:      "e.g. Patient Communication",
    milestoneYear:  "2025",
    milestoneEn:    "e.g. Graduated from Faculty of Dentistry",
    milestoneAr:    "مثال: تخرجت من كلية طب الأسنان",
    caseTitleEn:    "e.g. Class IV Composite Restoration",
    caseTitleAr:    "مثال: حشوة كومبوزيت (غرض اللغه العربيه هنا هو ان يفهم المرضى)",
    caseSubtitle:   "e.g. Treatment with composite",
  },
  buttons: {
    next:            "Next Step",
    previous:        "Previous",
    back:            "Back",
    addMilestone:    "Add Milestone",
    removeMilestone: "Remove",
    downloadToml:    "Download TOML File",
    sendWhatsApp:    "Send via WhatsApp (it is a MUST)",
    downloadPdf:     "Download CV as PDF",
    backHome:        "Back to Home",
    resetForm:       "Start New",
    finish:          "Submit Portfolio",
    submit:          "Submit",
  },
  caseCategories: [
    { id: "cosmetic",             en: "Cosmetic Dentistry",       ar: "تجميل الأسنان" },
    { id: "operative",            en: "Operative & Esthetics",    ar: "الحشو والتجميل" },
    { id: "prosthesis_fixed",     en: "Fixed Prosthodontics",     ar: "تركيبات ثابتة" },
    { id: "prosthesis_removable", en: "Removable Prosthodontics", ar: "تركيبات متحركة" },
    { id: "endodontics",          en: "Endodontics",              ar: "حشو العصب" },
    { id: "oral_surgery",         en: "Oral Surgery",             ar: "جراحة الفم" },
    { id: "periodontics",         en: "Periodontics",             ar: "أمراض اللثة" },
    { id: "orthodontics",         en: "Orthodontics",             ar: "تقويم الأسنان" },
    { id: "pediatric",            en: "Pediatric Dentistry",      ar: "طب أسنان الأطفال" },
    { id: "implant",              en: "Dental Implants",          ar: "زراعة الأسنان" },
  ] as CaseCategory[],
  pdf: {
    footerText:          "© 2026",
    primaryColor:        "#BB86FC",
    accentColor:         "#164e63",
    backgroundColor:     "#011017",
    textColor:           "#ffffff",
    mutedColor:          "#a8c7d8",
    lineColor:           "#0ab4fc",
    showCasesInPdf:      true,
    maxCasePhotosPerRow: 1,
  },
};

export default CONFIG;
